function [breakPointsCell, closeBreakPointPairs] = fcn_geometry_findBreakpoints(domains, tolerance, varargin)
% fcn_geometry_findBreakpoints
%
% This function takes the domains generated by Hough Segmentation,
% tolerance as the inputs and ouputs breakPointCell that contains the first
% and last point of the hough fits, type of hough fit, the parameters of
% the fit and the break points of the fitted curve. If the distance between
% two break points is less than or equal to this tolerance, they are
% considered as the close break point pairs
%
% FORMAT: 
%
% [breakPointsCell, closeBreakPointPairs] = fcn_geometry_findBreakpoints(domains, tolerance)
% 
% INPUTS:
%
% domains: the fitted domains of the segments, ordered from the fit
% that has the most points included, to the domain that has the least. The
% output of fcn_geometry_HoughSegmentation
%
% tolerance: the maximum distance between two break points to be considered
% as close break point pairs. 
%
% (OPTIONAL INPUTS)
% 
%      fig_num: a figure number to plot results. If set to -1, skips any
%      input checking or debugging, no figures will be generated, and sets
%      up code to maximize speed.
%
% OUTPUTS: 
%
% breakPointsCell: this cell struct array has the first and last point of
% all the hough fits, type of each hough fit, and the parameters of each
% fit.
%
% closeBreakPointPairs: This is a [N x 2 or 3] vector of close break point
% pairs of the fitted curve
%
% DEPENDENCIES:
%
%   fcn_DebugTools_checkInputsToFunctions
%
% EXAMPLES:
%      
% See the script: script_test_fcn_geometry_findBreakpoints
% for a full test suite.
%
% This function was written on 2024_02_11 by Aneesh Batchu
% Questions or comments? abb6486@psu.edu or sbrennan@psu.edu

% Revision History
% 2024_02_08 
% -- wrote the code - Aneesh Batchu
% 2024_02_11 
% -- modified the function to output
% the closeBreakPointPairs - Aneesh Batchu

flag_max_speed = 0;
if (nargin==3 && isequal(varargin{end},-1))
    flag_do_debug = 0; % Flag to plot the results for debugging
    flag_check_inputs = 0; % Flag to perform input checking
    flag_max_speed = 1;
else
    % Check to see if we are externally setting debug mode to be "on"
    flag_do_debug = 0; % Flag to plot the results for debugging
    flag_check_inputs = 1; % Flag to perform input checking
    MATLABFLAG_GEOMETRY_FLAG_CHECK_INPUTS = getenv("MATLABFLAG_GEOMETRY_FLAG_CHECK_INPUTS");
    MATLABFLAG_GEOMETRY_FLAG_DO_DEBUG = getenv("MATLABFLAG_GEOMETRY_FLAG_DO_DEBUG");
    if ~isempty(MATLABFLAG_GEOMETRY_FLAG_CHECK_INPUTS) && ~isempty(MATLABFLAG_GEOMETRY_FLAG_DO_DEBUG)
        flag_do_debug = str2double(MATLABFLAG_GEOMETRY_FLAG_DO_DEBUG);
        flag_check_inputs  = str2double(MATLABFLAG_GEOMETRY_FLAG_CHECK_INPUTS);
    end
end


if flag_do_debug
    st = dbstack; %#ok<*UNRCH>
    fprintf(1,'STARTING function: %s, in file: %s\n',st(1).name,st(1).file);
    debug_fig_num = 34838; %#ok<NASGU>
else
    debug_fig_num = []; %#ok<NASGU>
end

%% check input arguments
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   _____                   _       
%  |_   _|                 | |      
%    | |  _ __  _ __  _   _| |_ ___ 
%    | | | '_ \| '_ \| | | | __/ __|
%   _| |_| | | | |_) | |_| | |_\__ \
%  |_____|_| |_| .__/ \__,_|\__|___/
%              | |                  
%              |_| 
% See: http://patorjk.com/software/taag/#p=display&f=Big&t=Inputs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if 0==flag_max_speed
    if flag_check_inputs
        % Are there the right number of inputs?
        narginchk(2,3);

        % Check the tolerance input is a positive single number
        fcn_DebugTools_checkInputsToFunctions(tolerance, 'positive_1column_of_numbers',1);

    end
end

% Does user want to specify fig_num?
fig_num = []; % Default is to have no figure
flag_do_plots = 0;
if (0==flag_max_speed) && (3<= nargin)
    temp = varargin{end};
    if ~isempty(temp)
        fig_num = temp;
        flag_do_plots = 1;
    end
end

%% Main Code starts from here
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   __  __       _       
%  |  \/  |     (_)      
%  | \  / | __ _ _ _ __  
%  | |\/| |/ _` | | '_ \ 
%  | |  | | (_| | | | | |
%  |_|  |_|\__,_|_|_| |_|
% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

N_houghDomains = size(domains,2) - 1;

% Empty breakPoints domain structure
breakPoints.firstBreakPoint = [nan nan];
breakPoints.lastBreakPoint = [nan nan];
breakPoints.fitType = 'empty';
breakPoints.fitParameters = nan;

% Create a cell array to save the structure of each fit
breakPointsCell = cell(1,N_houghDomains);

% This loop saves the first and last points of each fit domain as the first
% and last break points in breakPointsCell cell array. This cell array also
% stores the fit type and parameters

breakPointsMatrix = zeros(2*N_houghDomains, 2);

for i = 1:N_houghDomains

    breakPointsCell{i} = breakPoints;
    breakPointsCell{i}.firstBreakPoint = domains{i}.points_in_domain(1,:);
    breakPointsCell{i}.lastBreakPoint = domains{i}.points_in_domain(end,:);
    breakPointsCell{i}.fitType = domains{i}.best_fit_type;
    breakPointsCell{i}.fitParameters = domains{i}.best_fit_parameters;

    % Saving the break points in an array to find the closest break points
    breakPointsMatrix(2*(i-1)+1,:) = breakPointsCell{i}.firstBreakPoint;
    breakPointsMatrix(2*i,:) = breakPointsCell{i}.lastBreakPoint;

end

% All possible 2 point combinations 
combos = nchoosek(1:size(breakPointsMatrix,1), 2);

% Find distances between the break points
distance_btw_breakpoints = (sum((breakPointsMatrix(combos(:,2),:) - breakPointsMatrix(combos(:,1),:)).^2,2)).^0.5;


% Finding the indices of break point close pairs
idx_breakpoint_close_pairs = combos(distance_btw_breakpoints <= tolerance,:);

% Reshaping the indices as a column matrix
idx_breakpoint_close_pairs_column = reshape(idx_breakpoint_close_pairs.', [], 1);

% Finding the break point close pairs 
closeBreakPointPairs = breakPointsMatrix(idx_breakpoint_close_pairs_column,:);

%% Plot the results (for debugging)?
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   _____       _                 
%  |  __ \     | |                
%  | |  | | ___| |__  _   _  __ _ 
%  | |  | |/ _ \ '_ \| | | |/ _` |
%  | |__| |  __/ |_) | |_| | (_| |
%  |_____/ \___|_.__/ \__,_|\__, |
%                            __/ |
%                           |___/ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if flag_do_plots
    figure(fig_num)

% Plotting the close break point pairs
plot(closeBreakPointPairs(:,1), closeBreakPointPairs(:,2), '.c');
xlabel('X');
ylabel('Y');
grid on;


end

if flag_do_debug
    fprintf(1,'ENDING function: %s, in file: %s\n\n',st(1).name,st(1).file);
end

end

%% Functions follow
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   ______                _   _
%  |  ____|              | | (_)
%  | |__ _   _ _ __   ___| |_ _  ___  _ __  ___
%  |  __| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
%  | |  | |_| | | | | (__| |_| | (_) | | | \__ \
%  |_|   \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
%
% See: https://patorjk.com/software/taag/#p=display&f=Big&t=Functions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%§


