% script_test_fcn_geometry_findBreakpointsOfAdjacentSegments.m
% tests fcn_geometry_findBreakpointsOfAdjacentSegments.m

% This script uses "fcn_geometry_HoughRegression.m" to fit the segments

% Revision History
% 2024_02_28 - Aneesh Batchu
% - Started the script

% To Do
% Add more cases

%% Clear workspace

close all

%%

rng(343)

figNum = -1;
% figNum = 115;

% Line 1 test points
seed_points = [1 2; 3.2 2];
M = 10;
sigma = 0.02;

test_points_LineSegment1 = fcn_geometry_fillLineTestPoints(seed_points, M, sigma, figNum);


% Line 2 test points
seed_points = [3.5 2; 6 2];
M = 10;
sigma = 0.02;

test_points_LineSegment2 = fcn_geometry_fillLineTestPoints(seed_points, M, sigma, figNum);
    
testpoints = [test_points_LineSegment1; test_points_LineSegment2];

% Corrupt the points
% figNum = 116;
% fig_NuM = figNum;
probability_of_corruption = 0.1;
magnitude_of_corruption = 3;

corrupted_testpoints = fcn_geometry_corruptPointsWithOutliers(testpoints,...
    (probability_of_corruption), (magnitude_of_corruption),figNum);

% Hough Segmentation
% figNum = 701;
figNum = -1;
transverse_tolerance = 0.05; % Units are meters
station_tolerance = 0.2; % Units are meters. 
threshold_max_points = 5;
input_points = corrupted_testpoints;

Hough_domains = fcn_geometry_HoughSegmentation(input_points, threshold_max_points, transverse_tolerance, station_tolerance, figNum);

% figNum = 601;
figNum = -1;
% Check the regression fit
regression_domains = fcn_geometry_HoughRegression(Hough_domains, [], figNum);
fig_nuM = figNum+2;
fcn_geometry_plotFitDomains(regression_domains, fig_nuM);

figNum = fig_nuM;
% [endPointsCell, sortedHoughSegmentEndPoints, ~] = fcn_geometry_sortRegressionDomains(regression_domains, 5, -1);
[~, sortedHoughSegmentEndPoints, ~] = fcn_geometry_sortRegressionDomains(regression_domains, 5, -1);


tolerance = 1;

endPointsMatrix = zeros(numel(sortedHoughSegmentEndPoints)/2, 2);

endPointsMatrix(1:2:end,:) = sortedHoughSegmentEndPoints(:,1:2);
endPointsMatrix(2:2:end,:) = sortedHoughSegmentEndPoints(:,3:4);

% [closeEndPointsMatrix, dist_btw_close_endPoints] = fcn_geometry_findEndPoints(endPointsMatrix(1,:), endPointsMatrix(2:end-1,:), endPointsMatrix(end,:), tolerance, -1);

curveStartPoint = sortedHoughSegmentEndPoints(1,1:2);
curveEndPoint = sortedHoughSegmentEndPoints(end,3:4);

intersectionPoints = fcn_geometry_findBreakpointsOfAdjacentSegments(curveStartPoint, sortedHoughSegmentEndPoints, curveEndPoint, figNum);

assert(isequal(round(intersectionPoints,4),[4.2773, 2.0001]));

% This function verifies the intersection point by substituting the intersection
% points into the line equation created using the "fit parameters"
% generated by "fcn_geometry_HoughSegmentation"

% [verifyIntersectionBool, LHs, RHs] = fcn_geometry_verifyIntersectionPoint(endPointsCell, intersectionPoints);
% 
% disp(LHs)
% disp(RHs)
% disp(verifyIntersectionBool)

%% Advanced test 1: Multiple segments were used to create a path 

rng(343)

% figNum = 901;
figNum = -1;

% Line test points - Line Segment 1
seed_points = [-15 0; -10 5];
M = 10;
sigma = 0.02;

test_points_line1 = fcn_geometry_fillLineTestPoints(seed_points, M, sigma, figNum);

% Line test points - Line Segment 2
seed_points = [-10 6; -1 6];
M = 10;
sigma = 0.02;

test_points_line2 = fcn_geometry_fillLineTestPoints(seed_points, M, sigma, figNum);

% Line test points - Line Segment 3 & 4 & 5
seed_points = [-2 4; 1 10; 7 4; 13 13];
M = 10;
sigma = 0.02;

test_points_line345 = fcn_geometry_fillLineTestPoints(seed_points, M, sigma, figNum);

% Line test points - Line Segment 6
seed_points = [10, 12; 18, 3];
M = 10;
sigma = 0.02;

test_points_line6 = fcn_geometry_fillLineTestPoints(seed_points, M, sigma, figNum);


testpoints = [test_points_line1; test_points_line2; test_points_line345; test_points_line6];

% Corrupt the points
% figNum = 801;
% fig_nuM = figNum;
probability_of_corruption = 0.1;
magnitude_of_corruption = 3;

corrupted_testpoints = fcn_geometry_corruptPointsWithOutliers(testpoints,...
    (probability_of_corruption), (magnitude_of_corruption),figNum);

% Hough Segmentation
% figNum = 701;
figNum = -1;
transverse_tolerance = 0.05; % Units are meters
station_tolerance = 0.5; % Units are meters. 
threshold_max_points = 20;
input_points = corrupted_testpoints;

Hough_domains = fcn_geometry_HoughSegmentation(input_points, threshold_max_points, transverse_tolerance, station_tolerance, figNum);

figNum = 1101;
fig_nuM = figNum;
% figNum = 601;
figNum = -1;
% Check the regression fit
regression_domains = fcn_geometry_HoughRegression(Hough_domains, [], figNum);
fcn_geometry_plotFitDomains(regression_domains, fig_nuM);




[~, sortedHoughSegmentEndPoints, ~] = fcn_geometry_sortRegressionDomains(regression_domains, 5, -1);

% endPointsMatrix = zeros(numel(sortedHoughSegmentEndPoints)/2, 2);
% 
% endPointsMatrix(1:2:end,:) = sortedHoughSegmentEndPoints(:,1:2);
% endPointsMatrix(2:2:end,:) = sortedHoughSegmentEndPoints(:,3:4);
% 
% tolerance = 5; 
% 
% [closeEndPointsMatrix, dist_btw_close_endPoints] = fcn_geometry_findEndPoints(endPointsMatrix(1,:), endPointsMatrix(2:end-1,:), endPointsMatrix(end,:), tolerance, figNum);
% 


curveStartPoint = sortedHoughSegmentEndPoints(1,1:2);
curveEndPoint = sortedHoughSegmentEndPoints(end,3:4);


intersectionPoints = fcn_geometry_findBreakpointsOfAdjacentSegments(curveStartPoint, sortedHoughSegmentEndPoints, curveEndPoint, fig_nuM);

assert(isequal(round(intersectionPoints(1,:),4),[-8.9621, 6.0359]));
assert(isequal(round(intersectionPoints(2,:),4),[-0.9904, 6.0509]));
assert(isequal(round(intersectionPoints(3,:),4),[0.9732, 10.0042]));
assert(isequal(round(intersectionPoints(4,:),4),[7.0013, 3.9991]));
assert(isequal(round(intersectionPoints(5,:),4),[11.3318, 10.4817]));

% This function verifies the intersection point by substituting the intersection
% points into the line equation created using the "fit parameters"
% generated by "fcn_geometry_HoughSegmentation"

% [verifyIntersectionBool, LHs, RHs] = fcn_geometry_verifyIntersectionPoint(endPointsCell, intersectionPoints);
% 
% disp(LHs)
% disp(RHs)
% disp(verifyIntersectionBool)

%% Advanced test : Multiple segments were used to create a path 

rng(343)

% figNum = 902;
figNum = -1;

% Line test points - Line Segment 1
seed_points = [-15 0; -10 5];
M = 10;
sigma = 0.02;

test_points_line1 = fcn_geometry_fillLineTestPoints(seed_points, M, sigma, figNum);

% Line test points - Line Segment 2
seed_points = [-8 6; -1 6];
M = 10;
sigma = 0.02;

test_points_line2 = fcn_geometry_fillLineTestPoints(seed_points, M, sigma, figNum);

% Line test points - Line Segment 3 & 4
seed_points = [-4 8; 2 0; 8 0];
M = 10;
sigma = 0.02;

test_points_line34 = fcn_geometry_fillLineTestPoints(seed_points, M, sigma, figNum);

% Line test points - Line Segment 5
seed_points = [6, -3; 10, 4];
M = 10;
sigma = 0.02;

test_points_line5 = fcn_geometry_fillLineTestPoints(seed_points, M, sigma, figNum);

% Line test points - Line Segment 6
seed_points = [12, 4; 16, 5];
M = 10;
sigma = 0.02;

test_points_line6 = fcn_geometry_fillLineTestPoints(seed_points, M, sigma, figNum);


testpoints = [test_points_line1; test_points_line2; test_points_line34; test_points_line5; test_points_line6];

% Corrupt the points
% figNum = 802;
% fig_nuM = figNum;
probability_of_corruption = 0.1;
magnitude_of_corruption = 3;

corrupted_testpoints = fcn_geometry_corruptPointsWithOutliers(testpoints,...
    (probability_of_corruption), (magnitude_of_corruption),figNum);

% Hough Segmentation
% figNum = 702;
figNum = -1;
transverse_tolerance = 0.05; % Units are meters
station_tolerance = 0.5; % Units are meters. 
threshold_max_points = 20;
input_points = corrupted_testpoints;

Hough_domains = fcn_geometry_HoughSegmentation(input_points, threshold_max_points, transverse_tolerance, station_tolerance, figNum);

% figNum = 602;
figNum = -1;
% Check the regression fit
regression_domains = fcn_geometry_HoughRegression(Hough_domains, [], figNum);

figNum =1102;
fig_nuM = figNum;
fcn_geometry_plotFitDomains(regression_domains, fig_nuM);

% figNum = fig_nuM;
% tolerance = 3;
% [endPointsCell, closeEndPointPairs, distance_btw_endpoints] = fcn_geometry_findBreakpoints(regression_domains, tolerance, figNum);


[~, sortedHoughSegmentEndPoints, ~] = fcn_geometry_sortRegressionDomains(regression_domains,5, -1);

% endPointsMatrix = zeros(numel(sortedHoughSegmentEndPoints)/2, 2);
% 
% endPointsMatrix(1:2:end,:) = sortedHoughSegmentEndPoints(:,1:2);
% endPointsMatrix(2:2:end,:) = sortedHoughSegmentEndPoints(:,3:4);
% 
% tolerance = 1; 
% 
% [closeEndPointsMatrix, dist_btw_close_endPoints] = fcn_geometry_findEndPoints(endPointsMatrix(1,:), endPointsMatrix(2:end-1,:), endPointsMatrix(end,:), tolerance, figNum);
% 


curveStartPoint = sortedHoughSegmentEndPoints(1,1:2);
curveEndPoint = sortedHoughSegmentEndPoints(end,3:4);

intersectionPoints = fcn_geometry_findBreakpointsOfAdjacentSegments(curveStartPoint, sortedHoughSegmentEndPoints, curveEndPoint, fig_nuM);

assert(isequal(round(intersectionPoints(1,:),4),[-8.9591, 6.0389]));
assert(isequal(round(intersectionPoints(2,:),4),[-2.4671, 5.9817]));
assert(isequal(round(intersectionPoints(3,:),4),[2.0287, 0.0687]));
assert(isequal(round(intersectionPoints(4,:),4),[7.7138, -0.0321]));
assert(isequal(round(intersectionPoints(5,:),4),[9.6552, 3.3934]));

% This function verifies the intersection point by substituting the intersection
% points into the line equation created using the "fit parameters"
% generated by "fcn_geometry_HoughSegmentation"

% [verifyIntersectionBool, LHs, RHs] = fcn_geometry_verifyIntersectionPoint(endPointsCell, intersectionPoints);
% 
% disp(LHs)
% disp(RHs)
% disp(verifyIntersectionBool)

%%
function print_results(distance,location) %#ok<DEFNU>
fprintf(1,'Distance \t Location X \t Location Y \n');
if ~isempty(distance)
    for i_result = 1:length(distance(:,1))
        fprintf(1,'%.3f \t\t %.3f \t\t\t %.3f\n',distance(i_result),location(i_result,1),location(i_result,2));
    end
end
end


