% This is a wrapper script to run all the test scripts in the geometry
% class library for the purpose of evaluating every assertion test in these
% files
script_test_fcn_geometry_checkInputsToFunctions;
script_test_fcn_geometry_circleCenterFrom3Points;
script_test_fcn_geometry_euclideanPointsToPointsDistance;
script_test_fcn_geometry_findAngleUsing2PointsOnCircle;
script_test_fcn_geometry_findAngleUsing3PointsOnCircle;
script_test_fcn_geometry_findIntersectionOfSegments;
script_test_fcn_geometry_findPhiConstraints;
script_test_fcn_geometry_findTangentPointFromPointToCircle;
script_test_fcn_geometry_findTangentPointsFromPointToCircle;
script_test_fcn_geometry_findTangentPointsTwoCircles;
script_test_fcn_geometry_findTangentPointTwoCircles;
script_test_fcn_geometry_findVisibleArcsFromPoints;
script_test_fcn_geometry_fitSlopeInterceptNPoints;
script_test_fcn_geometry_fitVectorToNPoints;
script_test_fcn_geometry_flagPointsCloserThanLineSegment;
script_test_fcn_geometry_flagPointsFurtherFromOrigin;
script_test_fcn_geometry_plotCircle;
script_test_fcn_geometry_polarLineFrom2PolarCoords;
script_test_fcn_geometry_selfCrossProduct;
